"""Added weights

Revision ID: 3e4b99432132
Revises: ca3dff835956
Create Date: 2025-05-13 10:47:18.411989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4b99432132'
down_revision = 'ca3dff835956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_winter_sports', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_advennture', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_outdoor', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_shopping', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_arts', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_road', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_wildlife', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_historical', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_beach', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_food', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_wine', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_education', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_culture', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_wellness', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_family', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_music', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_festival', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('weight_landmarks', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('weight_landmarks')
        batch_op.drop_column('weight_festival')
        batch_op.drop_column('weight_music')
        batch_op.drop_column('weight_family')
        batch_op.drop_column('weight_wellness')
        batch_op.drop_column('weight_culture')
        batch_op.drop_column('weight_education')
        batch_op.drop_column('weight_wine')
        batch_op.drop_column('weight_food')
        batch_op.drop_column('weight_beach')
        batch_op.drop_column('weight_historical')
        batch_op.drop_column('weight_wildlife')
        batch_op.drop_column('weight_road')
        batch_op.drop_column('weight_arts')
        batch_op.drop_column('weight_shopping')
        batch_op.drop_column('weight_outdoor')
        batch_op.drop_column('weight_advennture')
        batch_op.drop_column('weight_winter_sports')

    # ### end Alembic commands ###
