"""Added categories to user activities

Revision ID: 47e815025f00
Revises: c1f958bf497f
Create Date: 2025-05-13 18:43:48.066221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e815025f00'
down_revision = 'c1f958bf497f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_activity_preferences_activity_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_activity_preferences_activity_id_fkey', 'activities', ['activity_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
