"""Added columns

Revision ID: c242acc7eefe
Revises: 9d5c0df0e9b4
Create Date: 2025-05-13 07:01:59.910029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242acc7eefe'
down_revision = '9d5c0df0e9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('number_of_travelers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=True))
        batch_op.drop_constraint('user_preferences_passport_country_id_fkey', type_='foreignkey')
        batch_op.drop_column('passport_country_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('port_of_origin', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('country_residence', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('country_residence')
        batch_op.drop_column('port_of_origin')
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_country_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_preferences_passport_country_id_fkey', 'countries', ['passport_country_id'], ['id'])
        batch_op.drop_column('currency_code')
        batch_op.drop_column('number_of_travelers')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
